import enum
from dataclasses import dataclass
from enum import Enum, auto
from typing import Dict, Any, Optional


class CmdType(Enum):
    POWER = auto()  # {'state': False/True}
    FREE_DRIVE = auto()  # {'state': 0|1}
    EXECUTE_TRAJECTORY = auto()  # {'num': int}
    # EXECUTE_ROUTE = auto()  # {'num': int}
    EXECUTE_ACTION = auto()  # {'num': int}
    MOVE_TO_POINT = auto()  # {'name': str}
    GRIPPER_CMD = auto()  # {'index': int, 'value': bool}
    SHIFT_GRIPPER_CMD = auto()  # {'index': int, 'value': bool}
    REFRESH_WAYPOINTS = auto()
    STOP_MOVE = auto()
    SHUTDOWN = auto()
    FIND_NEAREST = auto()
    START_SIMPLE_JOYSTICK = auto()
    WAIT_VTOL_LIFT = auto()  # {'position': 'bottom'|'top', 'timeout_sec': int}


@dataclass
class Command:
    type: CmdType
    payload: Dict[str, Any] | None = None
    source: Optional[str] = None


class RobotPoints(enum.Enum):
    # pHomePosition = 1
    # pHelicopterModule = 2
    # pHelicopter1 = 3
    # pHelicopter1Payload = 4
    # pHelicopter2 = 5
    # pHelicopter2Payload = 6
    # pPayload = 7
    # pPayload1 = 8
    # pPayload2 = 9
    # pGrippers = 10
    # pGrippers1 = 11
    # pGrippers2 = 12
    # pCharger = 13
    # pCharger1 = 14
    # pCharger2 = 15
    # pVTOLModule = 16
    # pVTOL1 = 17
    # pVTOL1Payload = 18
    # pVTOL1Battery = 19
    # pVTOL2 = 20
    # pVTOL2Battery = 21
    # pVTOL2Battery2Charge = 22

    pUndefined = 0
    pHomePosition = 1
    pHelicopterModule = 2
    pHelicopter1 = 3
    pHelicopter1Payload = 4
    pHelicopter1InsideSlot = 5
    pHelicopter1BeforeSlot = 6
    pHelicopter2 = 7
    pHelicopter2Payload = 8
    pHelicopter2InsideSlot = 9
    pHelicopter2BeforeSlot = 10
    pPayload = 11
    pPayload1 = 12
    pPayload1InsideSlot = 13
    pPayload1BeforeSlot = 14
    pPayload2 = 15
    pPayload2InsideSlot = 16
    pPayload2BeforeSlot = 17
    pGrippers = 18
    pGrippers1 = 19
    pGrippers1InsideSlot = 20
    pGrippers1BeforeSlot = 21
    pGrippers2 = 22
    pGrippers2InsideSlot = 23
    pGrippers2BeforeSlot = 24
    pCharger = 25
    pCharger1 = 26
    pCharger1InsideSlot = 27
    pCharger1BeforeSlot = 28
    pCharger2 = 29
    pCharger2InsideSlot = 30
    pCharger2BeforeSlot = 31
    pVTOLModule = 32
    pVTOL1 = 33
    pVTOL1Payload = 34
    pVTOL1Battery = 35
    pVTOL1InsideBatterySlot = 36
    pVTOL1BeforeBatterySlot = 37
    pVTOL2 = 38
    pVTOL2Battery1 = 39
    pVTOL2InsideBattery1Slot = 40
    pVTOL2BeforeBattery1Slot = 41
    pVTOL2Battery2 = 42
    pVTOL2InsideBattery2Slot = 43
    pVTOL2BeforeBattery2Slot = 44
    pHomePosition_withSomeCargo = 45
    pHelicopterModule_withPL = 46
    pHelicopter1_withH1PL = 47
    pHelicopter1Payload_withH1PL = 48
    pHelicopter2_withH2PL = 49
    pHelicopter2Payload_withH2PL = 50
    pPayload_withPL = 51
    pPayload1_withPL = 52
    pPayload2_withPL = 53
    pCharger_withBatt = 54
    pCharger1_withBatt = 55
    pCharger2_withBatt = 56
    pVTOLModule_withSomeCargo = 57
    pVTOL1_withSomeCargo = 58
    pVTOL2_withBatt = 59
    pHelicopter1PayloadWithPL = 60
    pHelicopter1StickInSlot = 61
    pHelicopter1AfterSlot = 62
    pHelicopter2PayloadWithPL = 63
    pHelicopter2StickInSlot = 64
    pHelicopter2AfterSlot = 65
    pPayload1WithPL = 66
    pPayload1StickInSlot = 67
    pPayload1AfterSlot = 68
    pPayload2WithPL = 69
    pPayload2StickInSlot = 70
    pPayload2AfterSlot = 71
    pGrippers1WithGrip = 72
    pGrippers1StickInSlot = 73
    pGrippers1AfterSlot = 74
    pGrippers2WithGrip = 75
    pGrippers2StickInSlot = 76
    pGrippers2AfterSlot = 77
    pCharger1WithBatt = 78
    pCharger1StickInSlot = 79
    pCharger1AfterSlot = 80
    pCharger2WithBatt = 81
    pCharger2StickInSlot = 82
    pCharger2AfterSlot = 83
    pVTOL1PayloadWithPL = 84
    pVTOL1StickInPayloadSlot = 85
    pVTOL1AfterPayloadSlot = 86
    pVTOL1BatteryWithBatt = 87
    pVTOL1StickInBatterySlot = 88
    pVTOL1AfterBatterySlot = 89
    pVTOL2Battery1WithBatt = 90
    pVTOL2StickInBattery1Slot = 91
    pVTOL2AfterBattery1Slot = 92
    pVTOL2Battery2WithBatt = 93
    pVTOL2StickInBattery2Slot = 94
    pVTOL2AfterBattery2Slot = 95
    pVTOL2Battery2Charge = 96


class RobotTrajectories(enum.Enum):
    # tHomePosition_To_HelicopterModule = 1
    # tHelicopterModule_To_HomePosition = 2
    # tHelicopterModule_To_Helicopter1 = 3
    # tHelicopter1_To_HelicopterModule = 4
    # tHelicopter1_To_Helicopter1Payload = 5
    # tHelicopter1Payload_To_Helicopter1 = 6
    # tHelicopterModule_To_Helicopter2 = 7
    # tHelicopter2_To_HelicopterModule = 8
    # tHelicopter2_To_Helicopter2Payload = 9
    # tHelicopter2Payload_To_Helicopter2 = 10
    # tHomePosition_To_Payload = 11
    # tPayload_To_HomePosition = 12
    # tPayload_To_Payload1 = 13
    # tPayload1_To_Payload = 14
    # tPayload_To_Payload2 = 15
    # tPayload2_To_Payload = 16
    # tHomePosition_To_Grippers = 17
    # tGrippers_To_HomePosition = 18
    # tGrippers_To_Grippers1 = 19
    # tGrippers1_To_Grippers = 20
    # tGrippers_To_Grippers2 = 21
    # tGrippers2_To_Grippers = 22
    # tHomePosition_To_Charger = 23
    # tCharger_To_HomePosition = 24
    # tCharger_To_Charger1 = 25
    # tCharger1_To_Charger = 26
    # tCharger_To_Charger2 = 27
    # tCharger2_To_Charger = 28
    # tHomePosition_To_VTOLModule = 29
    # tVTOLModule_To_HomePosition = 30
    # tVTOLModule_To_VTOL1 = 31
    # tVTOL1_To_VTOLModule = 32
    # tVTOL1_To_VTOL1Payload = 33
    # tVTOL1Payload_To_VTOL1 = 34
    # tVTOL1_To_VTOL1Battery = 35
    # tVTOL1Battery_To_VTOL1 = 36
    # tVTOLModule_To_VTOL2 = 37
    # tVTOL2_To_VTOLModule = 38
    # tVTOL2_To_VTOL2Battery = 39
    # tVTOL2Battery_To_VTOL2 = 40

    tHomePosition_To_HelicopterModule=1
    tHomePosition_To_HelicopterModule_withPL=2
    tHelicopterModule_To_HomePosition=3
    tHelicopterModule_To_HomePosition_withSomeCargo=4
    tHelicopterModule_To_Helicopter1_withH1PL=5
    tHelicopterModule_To_Helicopter1=6
    tHelicopter1_To_HelicopterModule=7
    tHelicopter1_To_HelicopterModule_withPL=8
    tHelicopter1_To_Helicopter1Payload=9
    tHelicopter1_To_Helicopter1Payload_withH1PL=10
    tHelicopter1Payload_To_Helicopter1=11
    tHelicopter1Payload_To_Helicopter1_withH1PL=12
    tHelicopterModule_To_Helicopter2=13
    tHelicopterModule_To_Helicopter2_withH2PL=14
    tHelicopter2_To_HelicopterModule=15
    tHelicopter2_To_Helicopter2Payload=16
    tHelicopter2_To_Helicopter2Payload_withH2PL=17
    tHelicopter2Payload_To_Helicopter2=18
    tHelicopter2Payload_To_Helicopter2_withH2PL=19
    tHomePosition_To_Payload=20
    tHomePosition_To_Payload_withPL=21
    tPayload_To_HomePosition=22
    tPayload_To_HomePosition_withSomeCargo=23
    tPayload_To_Payload1=24
    tPayload_To_Payload1_withVTOL1PL=25
    tPayload1_To_Payload=26
    tPayload1_To_Payload_withVTOL1PL=27
    tPayload_To_Payload2=28
    tPayload_To_Payload2_withH1PL=29
    tPayload2_To_Payload=30
    tPayload2_To_Payload_withPL=31
    tHomePosition_To_Grippers=32
    tGrippers_To_HomePosition=33
    tGrippers_To_Grippers1=34
    tGrippers1_To_Grippers=35
    tGrippers_To_Grippers2=36
    tGrippers2_To_Grippers=37
    tHomePosition_To_Charger=38
    tHomePosition_To_Charger_withBatt=39
    tCharger_To_HomePosition=40
    tCharger_To_Charger1=41
    tCharger_To_Charger1_withVTOL1Batt=42
    tCharger1_To_Charger=43
    tCharger1_To_Charger_withVTOL1Batt=44
    tCharger_To_Charger2=45
    tCharger_To_Charger2_withBatt=46
    tCharger2_To_Charger=47
    tCharger2_To_Charger_withBatt=48
    tHomePosition_To_VTOLModule=49
    tHomePosition_To_VTOLModule_withSomeCargo=50
    tVTOLModule_To_HomePosition=51
    tVTOLModule_To_HomePosition_withSomeCargo=52
    tVTOLModule_To_VTOL1=53
    tVTOLModule_To_VTOL1_withSomeCargo=54
    tVTOL1_To_VTOLModule=55
    tVTOLModule_withSomeCargo=56
    tVTOL1_To_VTOL1Payload=57
    tVTOL1Payload_To_VTOL1=58
    tVTOL1_To_VTOL1Battery=59
    tVTOL1Battery_To_VTOL1=60
    tVTOL1Battery_To_VTOL1_withSomeCargo=61
    tVTOLModule_To_VTOL2=62
    tVTOLModule_To_VTOL2_withSomeCargo=63
    tVTOL2_To_VTOLModule=64
    tVTOL2_To_VTOLModule_withSomeCargo=65
    tVTOL2_To_VTOL2Battery1=66
    tVTOL2_To_VTOL2Battery2=67
    tVTOL2Battery1_To_VTOL2=68
    tVTOL2Battery1_To_VTOL2_withSomeCargo=69
    tVTOL2Battery2_To_VTOL2=70
    tVTOL2Battery2_To_VTOL2_withSomeCargo=71
    tHelicopter1Payload_To_Helicopter1InsideSlot=72
    tHelicopter1InsideSlot_To_Helicopter1BeforeSlot=73
    tHelicopter2Payload_To_Helicopter2InsideSlot=74
    tHelicopter2InsideSlot_To_Helicopter2BeforeSlot=75
    tPayload1_To_Grippers1InsideSlot=76
    tGrippers1InsideSlot_To_Grippers1BeforeSlot=77
    tGrippers1_To_Grippers1InsideSlot=78
    tGrippers2_To_Grippers2InsideSlot=79
    tGrippers2InsideSlot_To_Grippers2BeforeSlot=80
    tCharger1_To_Charger1InsideSlot=81
    tCharger1InsideSlot_To_Charger1BeforeSlot=82
    tCharger2_To_Charger2InsideSlot=83
    tCharger2InsideSlot_To_Charger2BeforeSlot=84
    tVTOL1Payload_To_VTOL1InsidePayloadSlot=85
    tVTOL1InsidePayloadSlot_To_VTOL1BeforePayloadSlot=86
    tVTOL1Battery_To_VTOL1InsideBatterySlot=87
    tVTOL1InsideBattery1Slot_To_VTOL1BeforeBatterySlot=88
    tVTOL2Battery1_To_VTOL2InsideBattery1Slot=89
    tVTOL2InsideBattery1Slot_To_VTOL2BeforeBattery1Slot=90
    tVTOL2Battery2_To_VTOL2InsideBattery2Slot=91
    tVTOL2InsideBattery2Slot_To_VTOL2BeforeBattery2Slot=92
    tHelicopter1PayloadWithPL_To_Helicopter1StickInSlot=93
    tHelicopter1StickInSlot_To_Helicopter1AfterSlot=94
    tHelicopter2PayloadWithPL_To_Helicopter2StickInSlot=95
    tHelicopter2StickInSlot_To_Helicopter2AfterSlot=96
    tPayload1WithPL_To_Grippers1StickInSlot=97
    tGrippers1StickInSlot_To_Grippers1AfterSlot=98
    tGrippers1WithGrip_To_Grippers1StickInSlot=99
    tGrippers2WithGrip_To_Grippers2StickInSlot=100
    tGrippers2StickInSlot_To_Grippers2AfterSlot=101
    tCharger1WithBatt_To_Charger1StickInSlot=102
    tCharger1StickInSlot_To_Charger1AfterSlot=103
    tCharger2WithBatt_To_Charger2StickInSlot=104
    tCharger2StickInSlot_To_Charger2AfterSlot=105
    tVTOL1PayloadWithPL_To_VTOL1StickInPayloadSlot=106
    tVTOL1StickInPayloadSlot_To_VTOL1AfterPayloadSlot=107
    tVTOL1BatteryWithBatt_To_VTOL1StickInBatterySlot=108
    tVTOL1StickInBattery1Slot_To_VTOL1AfterBatterySlot=109
    tVTOL2Battery1WithBatt_To_VTOL2StickInBattery1Slot=110
    tVTOL2StickInBattery1Slot_To_VTOL2AfterBattery1Slot=111
    tVTOL2Battery2WithBatt_To_VTOL2StickInBattery2Slot=112
    tVTOL2StickInBattery2Slot_To_VTOL2AfterBattery2Slot=113


class RobotActions(enum.Enum):
    aVTOL2_To_VTOL2Battery = 1
    aVTOL2Battery_To_VTOL2 = 2
