# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/params_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_ParamsDialog(QDialog):
    def __init__(self, slave, parent=None):
        super().__init__(parent)

        self.parent = parent
        self.slave = slave

        self.setFixedSize(400, 180)
        self.setWindowTitle('Parameters')

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(30, 140, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.SlaveID = QtWidgets.QTextEdit(self)
        self.SlaveID.setGeometry(QtCore.QRect(100, 20, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlaveID.sizePolicy().hasHeightForWidth())
        self.SlaveID.setSizePolicy(sizePolicy)
        self.SlaveID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlaveID.setObjectName("SlaveID")
        self.Quantity = QtWidgets.QTextEdit(self)
        self.Quantity.setGeometry(QtCore.QRect(100, 80, 61, 21))
        self.Quantity.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Quantity.setObjectName("Quantity")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.StartRegister = QtWidgets.QTextEdit(self)
        self.StartRegister.setGeometry(QtCore.QRect(100, 50, 61, 21))
        self.StartRegister.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StartRegister.setObjectName("StartRegister")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept)  # type: ignore
        self.buttonBox.rejected.connect(self.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

        self.buttonBox.accepted.connect(self.set_params)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.accepted.connect(self.accept)

        self.StartRegister.setText(str(self.slave.params["registeraddress"]))
        self.SlaveID.setText(str(self.slave.params["slave_id"]))
        self.Quantity.setText(str(self.slave.params["number_of_registers"]))

    def set_params(self):
        self.slave.params['slave_id'] = int(self.SlaveID.toPlainText())
        self.slave.params['registeraddress'] = int(self.StartRegister.toPlainText())
        self.slave.params['number_of_registers'] = int(self.Quantity.toPlainText())

        for key, val in self.slave.params.items():
            print(key, val)
        print()

    def retranslateUi(self, ParamsDialog):
        _translate = QtCore.QCoreApplication.translate
        ParamsDialog.setWindowTitle(_translate("ParamsDialog", "Slave 2 parameters"))
        self.label.setText(_translate("ParamsDialog", "Slave ID"))
        self.label_6.setText(_translate("ParamsDialog", "Quantity"))
        self.label_5.setText(_translate("ParamsDialog", "Start reg"))
