# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/write_single_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_WriteRegDialog(QDialog):
    def __init__(self, slave, parent=None):
        super().__init__(parent)

        self.parent = parent
        self.slave = slave

        self.setFixedSize(340, 180)
        self.setWindowTitle('Write single register')

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(90, 140, 231, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.SlaveID = QtWidgets.QTextEdit(self)
        self.SlaveID.setGeometry(QtCore.QRect(100, 20, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlaveID.sizePolicy().hasHeightForWidth())
        self.SlaveID.setSizePolicy(sizePolicy)
        self.SlaveID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlaveID.setObjectName("SlaveID")
        self.Value = QtWidgets.QTextEdit(self)
        self.Value.setGeometry(QtCore.QRect(100, 80, 61, 21))
        self.Value.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Value.setObjectName("Value")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Address = QtWidgets.QTextEdit(self)
        self.Address.setGeometry(QtCore.QRect(100, 50, 61, 21))
        self.Address.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Address.setObjectName("Address")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.checkBoxSigned = QtWidgets.QCheckBox(self)
        self.checkBoxSigned.setGeometry(QtCore.QRect(240, 80, 81, 20))
        self.checkBoxSigned.setObjectName("checkBoxSigned")

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept)  # type: ignore
        self.buttonBox.rejected.connect(self.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

        self.buttonBox.accepted.connect(self.set_write_params)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.accepted.connect(self.accept)

        self.Address.setText("1")
        self.SlaveID.setText(str(self.slave.params["slave_id"]))
        self.Value.setText("1")

        self.checkBoxSigned.setChecked(True)

    def set_write_params(self):
        self.slave.write_reg_params['slave_id'] = int(self.SlaveID.toPlainText())
        self.slave.write_reg_params['registeraddress'] = int(self.Address.toPlainText())
        self.slave.write_reg_params['value'] = float(self.Value.toPlainText())
        self.slave.write_reg_params['signed'] = bool(self.checkBoxSigned.isChecked())

        self.slave.write(self.parent.ui.LabelMessage_5)

    def retranslateUi(self, WriteRegDialog):
        _translate = QtCore.QCoreApplication.translate
        WriteRegDialog.setWindowTitle(_translate("WriteRegDialog", "Write single register"))
        self.label.setText(_translate("WriteRegDialog", "Slave ID"))
        self.label_6.setText(_translate("WriteRegDialog", "Value"))
        self.label_5.setText(_translate("WriteRegDialog", "Address"))
        self.checkBoxSigned.setText(_translate("WriteRegDialog", "Signed"))
